# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170307_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-timestamp']},
        ),
    ]
